version: "3.0"
services:
  redis:
    image: redis
  db:
    image: postgres:9.4
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
  vote:
    build: ./vote
    depends_on:
      - redis
    ports:
      - 80:80
  worker:
    build: ./worker
    depends_on:
      - db
      - redis
  result:
    build: ./result
    depends_on:
      - db
    ports:
      - 81:80
